apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: devops-catalog
  region: us-east-2
  version: "1.23"
managedNodeGroups:
- name: primary-1-23
  instanceType: t2.small
  minSize: 3
  maxSize: 6
  spot: true
